project:
  type: website
  output-dir: docs

website:
  page-navigation: false
  title: "The International Fossil Coral and Reef Society"
  description: "All things fossil corals, sponges, and reef ecosystems in the broadest sense"
  site-url: https://ifcrs.org
  repo-url: https://github.com/TheIFCRS/IFCRS/tree/gh-pages
  open-graph:
    image: "/images/logo.png"
  twitter-card:
    image: "/images/logo.png"
    creator: "@LewisAlanJones"
    site: "@fossil_reef"
  favicon: "/images/logo.png"
  image: "/images/twitter-card.png"
  navbar:
    title: "The International Fossil Coral and Reef Society"
    logo: "/images/logo.png"
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - text: About
        menu:
           - href: council/index.qmd
             text: Council
           - href: statute/index.qmd
             text: Statue
           - href: history/index.qmd
             text: History
      - href: membership/index.qmd
        text: Membership
      - href: meetings/index.qmd
        text: Meetings
      - href: news/index.qmd
        text: News
      - href: gallery/index.qmd
        text: Gallery
      - href: resources/index.qmd
        text: Resources
      - href: proceedings/index.qmd
        text: Proceedings
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/ifcrs.bsky.social
        aria-label: "Bluesky"


  page-footer:
    border: true
    right: "The International Fossil Coral and Reef Society"
    left: "&copy; Copyright 2025, IFCRS"
    center:
      - text: "{{< iconify fa6-brands:bluesky >}}"
        href: https://bsky.app/profile/ifcrs.bsky.social
        aria-label: "Bluesky"
    background: "lightgrey"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: false
    link-external-newwindow: true
    link-external-icon: false
    page-layout: full