---
title: "General Data Protection Regulation - Terms and Conditions"
---

I confirm that I am at least 16 year of age or older.

I have read and accept any EULA, Terms and Conditions, Acceptable Use Policy, and/or Data Processing Addendum which has been provided to me in connection with the software, products and/or services.

I have been fully informed and consent to the collection and use of my personal data for any purpose in connection with the software, products and/or services.

I understand that certain data, including personal data, must be collected or processed in order for you to provide any products or services I have requested or contracted for. I understand that in some cases it may be required to use cookies or similar tracking to provide those products or services.

I understand that I have the right to request access annually to any personal data you have obtained or collected regarding me. You have agreed to provide me with a record of my personal data in a readable format.

I also understand that I can revoke my consent and that I have the right to be forgotten. If I revoke my consent you will stop collecting or processing my personal data. I understand that if I revoke my consent, you may be unable to provide contracted products or services to me, and I can not hold you responsible for that.

Likewise, if I properly request to be forgotten, you will delete the data you have for me, or make it inaccessible. I also understand that if there is a dispute regarding my personal data, I can contact someone who is responsible for handling data-related concerns. If we are unable to resolve any issue, you will provide an independent service to arbitrate a resolution. If I have any questions regarding my rights or privacy, I can contact the email address provided.
