---
title: "Meetings"
toc: true
---

# International Fossil Coral and Reef Society

|      |                                                                                                                                 |
|------------------|------------------------------------------------------|
| 2024 | **Online** - Chengdu & Nanjing, China (3^rd^ Early Career Researcher Symposium)                                                 |
| 2023 | [**Chęciny, Poland**](https://fossilcoralreefs.com) (14^th^ International Symposium Fossil Coral and Reef Society)              |
| 2022 | **Online** - Erlangen, Germany (2^nd^ Early Career Researcher Symposium)                                                        |
| 2021 | **Online** - Vigo, Spain & Vienna, Austria (1^st^ Early Career Researcher Symposium)                                            |
| 2019 | [**Modena, Italy**](https://www.13thfossilcnidaria.unimore.it) (13^th^ International Symposium on Fossil Cnidaria and Porifera) |
| 2015 | **Muscat, Oman** (12^th^ International Symposium on Fossil Cnidaria and Porifera)                                               |
| 2011 | **Liege, Belgium** (11^th^ International Symposium on Fossil Cnidaria and Porifera)                                             |
| 2007 | **St. Petersburg, Russia** (10^th^ International Symposium on Fossil Cnidaria and Porifera)                                     |
| 2003 | **Graz, Austria** (9^th^ International Symposium on Fossil Cnidaria and Porifera)                                               |
| 1999 | **Sendai, Japan** (8^th^ International Symposium on Fossil Cnidaria and Porifera)                                               |
| 1995 | **Madrid, Spain** (7^th^ International Symposium on Fossil Cnidaria and Porifera)                                               |
| 1991 | **Muenster, Germany** (6^th^ International Symposium on Fossil Cnidaria and Porifera)                                           |
| 1988 | **Brisbane, Australia** (5^th^ International Symposium on Fossil Cnidaria and Porifera)                                         |
| 1983 | **Washington, USA** (4^th^ International Symposium on Fossil Cnidaria and Porifera)                                             |
| 1979 | **Warsaw, Poland** (3^rd^ International Symposium on Fossil Cnidaria and Porifera)                                              |
| 1975 | **Paris, France** (2^nd^ International Symposium on Fossil Cnidaria and Porifera)                                               |
| 1971 | **Novosibirsk, Russia** (1^st^ International Symposium on Fossil Cnidaria and Porifera)                                         |

# Other meetings

|      |                                                                                            |
|------------------|------------------------------------------------------|
| 2024 | [**Le Castella, Italy**](resources/algae/circular.pdf) (13^th^ International Symposium on Fossil Algae)
| 2024 | [**Napoli, Italy**](https://ecrs2024.eu) (European Coral Reef Symposium 2024)              |
| 2023 | [**Bremen, Germany**](https://www.icrs2022.de) (15^th^ International Coral Reef Symposium) |

**Do you have any meetings to add? [Get in contact.](mailto:lewis@ifcrs.org)**
