---
title: "IFCRS - Membership Application"
toc: true
---

The International Fossil Coral and Reef Society (IFCRS) welcomes anyone interested in fossil corals, sponges and reef ecosystems in the broadest sense. Researchers and students are the core of our Society, but general enthusiasts are also warmly encouraged to join our growing community.


Benefits of becoming a member:

- Receive communications from our IFCRS mailing list
- Vote at Society meetings on all matters concerning the Society, including electing new Council Members at our meetings
- Submit announcements for publication on the IFCRS website and social media accounts
- Apply to participate in the IFCRS activities, including our symposium to be held every 4 years (the next is in Poland in 2023)
- For the moment membership is free of charge. We plan to collect some fees in the future, but those will always be very reasonable.

Please register here: [IFCRS - Membership Application](https://www.cnidaria.nat.uni-erlangen.de/IFCRS/registration.php)