---
title: "Conference Proceedings"
---

-   [Bosellini FR, Papazzoni CA, Vescogni A (eds) 2020. Paleo-archives of Cnidaria and Porifera in space and time. Bollettino della Società Paleontologica Italiana, 59/4, 183-354.](./resources/proc-2020.pdf)

-   [Denayer J, Aretz M, Poty E (eds) 2012. Proceedings of the 11th International Symposium on Fossil Cnidaria and Sponges, Liège, August 22-26, 2011. Geologica Belgica, 15/4, 200-400.](./resources/proc-2012.pdf)

-   [Kossovaya O, Somerville I (eds) 2010. Fossil corals archaeocyaths and sponges. Proceedings of the 10th International Symposium on Fossil Cnidaria and Sponges. Palaeoworld, 19, 209-434.](./resources/proc-2010.pdf)

-   Hubmann B, Piller W (eds) 2007. Fossil Corals and Sponges. Proceedings of the 9th International Symposium on Fossil Cnidaria and Sponges, Graz 2003. Schriftenreihe der Erdwissenschaftlichen Komissionen, 17, 531 pp.

-   Ezaki Y, Mori K, Sugiyama T, Sorauf JE (eds) 2002. Proceedings of the 8th International Symposium on Fossil Cnidaria and Sponges, September 12-16, 1999, Sendai, Japan. Bulletin of the Tohoku University Museum, 1, 341 pp.

-   Perejón A (ed) 1997. Proceedings of the VII International Symposium on Fossil Cnidaria and Porifera: held in Madrid, Spain, 1995. Boletín de la Real Sociedad Española de Historia Natural. Sección geológica, 91, 378 pp., 92, 392 pp.

-   Oekentorp-Küster P (ed) 1993. 1994. Proceedings of the VI. International Symposium on Fossil Cnidaria and Porifera held in Münster, Germany 9.-14. September 1991. Courier Senckenberg, 164, 372 pp., 172, 430 pp.

-   Jell PA, Pickett JW (eds) 1989. Fossil Cnidaria 5: proceedings of the Fifth International Symposium on Fossil Cnidaria including Archaeocyatha and Spongiomorphs held in Brisbane, Queensland, Australia, 25-29 July 1988. Memoir of the Association of Australasian Palaeontologists, 8, 438 pp.

-   [Oliver Jr. WA, Sando WJ, Cairns SD, Coates AG, Macintyre IG, Bayer FM, Sorauf JE (eds) 1984. Recent Advances in the Paleobiology and Geology of the Cnidaria. Proceedings of the Fourth International Symposium on Fossil Cnidaria (and Archaeocyathids and Stromatoporoids) held in Washington, DC, U.S.A., August, 1983. Palaeontographica Americana, 54, 557 pp.](https://www.biodiversitylibrary.org/page/28035197#page/5/mode/1up)

-   [Osmolska H, Roniewicz E et al. (eds) 1980 (1981). Third International Symposium on Fossil Cnidarians, Warszawa, 1979. Acta Palaeontologica Polonica, 25(3-4), pp. 291-679 (English and French).](https://www.app.pan.pl/issue.html?issue=99)

-   [Chevalier J-P (ed) 1977. Second Symposium International sur les coraux et récifs coralliens fossiles, Paris, 1975. Mémoires du B.R.G.M., 89, 542 pp.](https://ia904708.us.archive.org/18/items/palaeontographic541984pale/palaeontographic541984pale.pdf)

-   Sokolov BS, Dubatolov VN, Ivanovski AB (eds) 1974. 1975. Ancient Cnidaria. Academy of Sciences USSR, Siberian Branch, Transactions of the Institute of Geology and Geophysics, 201, 364 pp., 202, 280 pp.
