---
title: "Resources"
toc-depth: 1
---

# Databases

## WoRMS

[World Register of Marine Species](https://www.marinespecies.org/index.php) (WoRMS) provides an online register of scientific names of all marine organisms. In this continuously updated list, users can find the taxonomic classification of scleractinians, with valid and invalid names of families, genera and species. The efforts of the Corallosphere working group (see below) have recently been integrated into WoRMS.

## Corallosphere

[Corallosphere](http://www.corallosphere.org) is a web application developed with the aim of exploring new approaches to compiling taxonomic information on extant and extinct scleractinian corals. Main areas covered in Corallosphere include text descriptions for diagnoses of valid genera, as well as tools for managing taxonomic synonymies, image databases, a bibliography, and an illustrated atlas of morphological terms.

## The Paleobiology Database

[The Paleobiology Database](https://paleobiodb.org/#/) is an online resource for information on the distribution and classification of fossil animals, plants, and microorganisms. The database contains more than 1,500,000 fossil occurrences from more than 200,000 collections, including many fossil Cnidaria, Porifera and reef organisms.

## The PaleoReefs Database

[The PaleoReefs Database](https://www.paleo-reefs.pal.uni-erlangen.de) (PARED) is a major resource on fossil reef systems. PARED has been developed by Prof. Wolfgang Kiessling since 1995 with the aim to collect data on Phanerozoic reefs in a standardised format and to use those data for tracing patterns and processes in reef development. PARED currently holds data on more than 4000 Phanerozoic reef sites with geological, geographical, and paleontological information on every reef.

## Archaeocyatha - A knowledge base

[The database](http://archaeocyatha.infosyslab.fr) contains data on 307 genera with systematics information and types pictures. The taxa are described by 122 descriptors of which 87 are morphological, 8 pertain to stratigraphy and geography and the remaining 27 are taken from traditional classification. Descriptors and states are defined and illustrated. They are included inside a website in three parts with different types of information. The first is with general information about Archaeocyatha with an introduction; their role in Cambrian system, their morphology and a bibliography. The second part is about the database. It contains general remarks on its structure and some exports: list of genera and their detailed sheets, list of descriptors, list of groups of descriptors and the base properties. The third and last part concerns the interactive key and its tools: user guide, matching terminologies and glossary.

# Treatise

Treatise Online no. 149: Part F, Revised, Volume 2, Chapter 16: [Systematic descriptions of the Scleractinia family Fungiacyathidae](https://doi.org/10.17161/to.vi.15389)	R. C. Baron-Szabo, S. D. Cairns, Jarosław Stolarski	Treatise - Article	2021

Treatise Online no. 144: Part F, Revised, Volume 2, Chapter 15: [Systematic descriptions of the Scleractinia family Negoporitidae](https://doi.org/10.17161/to.vi.15112)	R. C. Baron-Szabo	Treatise - Article	2021

Treatise Online no. 119: Part F, Revised, Volume 2, Chapter 14: [Systematic descriptions of the Scleractinia family Dendrophylliidae](https://doi.org/10.17161/to.v0i0.9825)	R. C. Baron-Szabo, Stephen D. Cairns	Treatise - Article	2019

Treatise Online no. 105: Part F, Revised, Volume 2, Chapter 13: [Systematic descriptions of the Scleractinia family Pachyphylliidae](https://doi.org/10.17161/to.v0i0.7551)	R. C. Baron-Szabo	Treatise - Article	2018

Treatise Online no. 99: Part F, Revised, Volume 2, Chapter 12: [Systematic descriptions of the Scleractinia family Rhipidastraeidae](https://doi.org/10.17161/to.v0i0.6672)	R. C. Baron-Szabo	Treatise - Article	2017

Treatise Online no. 98: Part F, Revised, Volume 2, Chapter 11: [Systematic descriptions of the Scleractinia family Micrabaciidae](https://doi.org/10.17161/to.v0i0.6671)	R. C. Baron-Szabo, Stephen D. Cairns	Treatise - Article	2017

Treatise Online no. 80: Part F, Volume 2, Chapter 10: [Systematic Descriptions of the Scleractinia Family Rhizangiidae](https://doi.org/10.17161/to.v0i0.6462) R. C. Baron-Szabo, S. D. Cairns	Treatise - Article	2016

# Online collections

[Natural History Museum (UK) Data Portal](https://data.nhm.ac.uk/) - Only database to explore and download the Museum’s research and collections data.

[Oxford University Museum Collections Online](https://oumnh.ox.ac.uk/collections-online#/search) - Museum’s specimen, object and archive collections.

[Estonian National Geocollections Database](https://geoloogia.info/search) - Browse the museum's geocollections.

**Do you have more resources to recommend? [Get in contact](mailto:lewis@ifcrs.org).**
