---
title: "Happy holidays and New Year 2024"
description: "A message from the IFCRS President and Secretary"
author: "Jarek Stolarski and Nadia Santodomingo"
date: "2023-12-29"
---

Dear members of IFCRS, colleagues and friends,

We are happy to arrive at the end of yet another successful year for our society. The most remarkable event was that after four long years - and overcoming a pandemic- we could finally meet in person at the European Centre for Geological Education (Chęciny, Poland) to enjoy the interesting scientific programme of our 14th IFCRS meeting, besides “going deeper” into a rich cultural and geological agenda at many other places around Poland.
In the general assembly, we collectively elected new council members Kun Liang, Thomas Stemmann and Danijela Dimitrijevic, while giving continuity to Markus Aretz, Lewis Jones, Angelina Ivkic, Julien Denayer, Jarek Stolarski and Nadia Santodomingo. We sincerely acknowledge our leaving council members Francesca Bosellini, Wolfgang Kiessling, Nancy Budd, Graham Young and Christina Krause for their hard work on bringing up our society with new branding, social media presence and a suite of novel activities over the past few years. We also awarded our colleague Brian Rosen with the Milne Edwards Medal for his important scientific contributions to our field. We voted that our next 15th IFCRS meeting would be in Toulouse (France) in 2027 thanks to the kind offer presented by Markus Aretz. As announced, publication of the proceedings of the 14th IFCRS conference is planned in international peer reviewed journal Acta Palaeontologica Polonica ([https://www.app.pan.pl/](https://www.app.pan.pl/)). Detailed guidelines will be announced soon.

During 2023 we marked the second year of the successful **online IFCRS Lectures Series**. The winter/spring lectures were presented by Jarek Stolarski, Francesca Bosellini, Andrea Quattrini, Paolo Montagna, and Stephen Kershaw, to give a great closure in the Autumn with Mikołaj Zapalski. The calendar for 2024 will be advertised early next year. We appreciate the loyal attendance of our colleagues all over the world who actively engage in fruitful discussions, as well as we thank our lecturers for generously sharing their expertise.
Thanks to the diligent work of Lewis Jones, we are pleased to launch the new **Society’s website** [https://ifcrs.org/](https://ifcrs.org/). We will continue sharing news and activities there and through our social media accounts on Twitter (now X) “[@fossil_reef](https://twitter.com/fossil_reef)” and Instagram “[fossil_reef](https://www.instagram.com/fossil_reef/)”. We encourage you to follow us on those channels and contribute with content, photos, and news by tagging our handles or sending us an email to [fossilcoralreef@gmail.com](mailto:fossilcoralreef@gmail.com).

While we wait to see each other again in four years, we are happy to announce that the **Third IFCRS Early Career Researcher Symposium**, will be led by our Chengdu and Nanjing ECR colleagues. We expect that these yearly ECR meetings will keep offering a stage for our enthusiastic young members to present their exciting novel research. Equally, we would like to extend the invitation to the symposium “Reef paleoecology in time and space” organised by our colleagues Aaron O’Dea, Rowan Martindale and Katie Cramer as part of the 12th North American Paleontological Convention (NAPC) at the University of Michigan (June 17-21, 2024).
We hope to see many of you attending our activities for the next year. On behalf of the Council, we wish a happy New Year 2024 to you and your loved ones.