---
title: "Statute of the International Fossil Coral and Reef Society"
title-block-banner: true
---

**Adopted at the General Assembly in Modena, Italy (6^th^ September 2019)**

**Article 1. Name.**

The name of the Society is International Fossil Coral and Reef Society. It was founded as International Association for the Study of Fossil Cnidaria and Porifera in Nowosibirsk in 1971.

**Article 2. Purpose.**   

The objectives of the Society are to facilitate and promote scientific knowledge in the field of fossil corals, sponges and reefs and their related environments and to promote their study in the broadest possible international context.

The Society aims:

- a. to discuss and compare scientific research on fossil corals, sponges and reefs and their related environments;
- b. to encourage the exchange of scientific research, in particular involving international cooperation;
- c. to promote integration with other scientific disciplines. 

**Article 3. Location.**

The location of its center is that of the President. 

**Article 4. Membership.**

The Society distinguishes between two categories of members: ordinary members and student members (collectively referred to as the “members”).

Any person interested in the Society’s activities can become a member. All members are equal and possess the same rights. 

The Secretary shall maintain a register in which the names and addresses of all members shall be recorded. Each member shall provide his or her address and e-mail address to the Secretary, which shall keep the register up to date.

Membership as a student member is open to persons that have enrolled under the undergraduate, MSc or PhD student status at a higher education institute. They are required to produce proof of their student status by means of a certificate of enrolment or by means of a statement provided by their supervisor.

**Article 5. Membership Fee.**

Ordinary Members and Student Members shall pay an Annual Membership Fee. The amount payable shall be set by the General Assembly. These Membership fees are used to support the aims of the society; especially the support for students and Early career scientist and scientists from developing countries to attend the activities organized by the Society.
The secretary reports on the use of the fees during the general assembly to all members and annually to the Council. 

**Article 6. Resignation and termination of membership.**

Membership in this Society can be lost:

- a. by resignation
- b. through elimination by the Council for non-payment of the membership fee or 
- c. for any reason of gravity, the member concerned having been previously requested to provide an explanation. 

**Article 7. The Council.**

The Society is governed by a Council composed of:
- a President (the Chair of the Current Symposium)
- a vice-President (the Chair of the next Symposium)
- a Secretary/Treasurer (nominated by the President)
- four regular Councilors
- a representative of the website
- a representative for Students and Early Scientists

The President, Vice-President, Secretary/Treasurer and website member are nominated during the General Assembly. Customarily, the President will be the organizer/Convenor of the Symposium at which he or she takes office. The Secretary is appointed by the President with the approval of the Council.

The four regular Councilors are elected by the Association members during the General Assembly. Candidacies for the role of Councilor should be declared to the Council at least one month before the General Assembly.

The representative for Students and Early Scientists is elected among and by all student members and ordinary members who finished their PhD in the last 5 years. The election takes place at the General Assembly and all candidates have to be present at the General Assembly. 

All Council members have full voting rights and should serve not more than two terms. The Council is encouraged to meet at least two times during the term and can communicate and take decisions electronically adopted by the simple majority. 

**Article 8. General Assembly.**

The General Assembly is composed of the Society members present at a properly called meeting. It is convoked at the time of the Symposium, in principle every 3 to 5 years.

The General Assembly can modify by a vote the Statute, upon proposal by one of the Society members.

Any decision voted upon in the General Assembly must be adopted by the simple majority. 

**Article 9. Symposium.**

The Symposium can be organized by a member of the Society nominated to this end. 

Proposals for the organization of an International Symposium must be submitted to the Council at least 2 months before the next preceding Symposium. Such proposals are to be voted by the General Assembly. 

The organizer of the Symposium alone is enabled to establish the modalities for organizing a meeting and fixing the participation fee for all participants.

Symposium participants who are not members of the Society cannot vote or participate in the governance of the Society. 

**Article 10. Communication.**

The official language of the Society is English. 

The web site of the Society is the only official medium for all communication and information about the Society’s activities to members and to the world community. The Council has authority to determine the site and contents of the web site and to appoint or hire a web master. The same rules are applied to any social media activities developed in the future.

**Article 11. Duration.**

The duration of the Society is unlimited. 

Dissolution of the Society can be pronounced by the General Assembly or by the membership through a mail ballot.