---
title: "4^th^ Early Career Researcher Symposium"
subtitle: "📆 13th November 2025 | ⏰ 09:00–16:00 UTC | [Register](https://fau.zoom-x.de/meeting/register/51P0jF4fTy6nLp3GzT5QSg)"
title-block-banner: true
---

## About the symposium

Thank you for your interest in the 4^th^ Early Career Researcher Symposium (ECRS2025) of the International Fossil Coral and Reef Society! 

The symposium is a one-day online, free-to-attend event, with the aim of filling the gap between the four-year cycle of our main symposium (every four years). The event is open to researchers of all career stages, with talks delivered exclusively by invited Early Career Researchers.

As part of the symposium, we will have 'Meet the Lab' presentations, in which different labs from all around the world will talk about their research themes and any opportunities available---a perfect opportunity to network with fellow researchers and encourage future collaborations.

On behalf of the organising committee, we look forward to seeing many of you there!

Lewis A. Jones, Danijela Dimitrijević, Alison Cribb, and Amanda Godbold 🪸

[Register | ECRS 2025](https://fau.zoom-x.de/meeting/register/51P0jF4fTy6nLp3GzT5QSg){.button}
[Download | Abstract Book](abstract-book-2025.pdf){.button}

***If you are leading a working group, and would like to present your lab at the symposium, please also register your interest**

## Plenary talk

### Fossil clues to reef resilience: The critical role of palaeontology in coral reef conservation  
**Dr Nadia Santodmingo - Senckenberg Forschungsinstitut und Naturmuseum Frankfurt, Germany**

Coral reefs are undergoing unprecedented decline under accelerating climate change, with almost half of reef-building coral species at risk of extinction due to mass bleaching, disease, overfishing, and pollution. Projections are gloomy and suggest that even the most diverse reefs will struggle to keep pace with future warming. In the midst of the crisis, coral reef decline is not uniform, showing high variability at different scales. Some regions, such as the Coral Triangle, have maintained relatively stable coral cover despite shifts in species dominance. Some taxa, such as slow-growing Porites, appear more resistant than fast-growing Acropora and Pocillopora. And along the depth–light gradient, mesophotic coral ecosystems show greater resilience to thermal extremes compared to euphotic shallow reefs. These differences in the spectrum of reef resilience pose pressing questions. Why do some regions collapse while others defeat decline? Which traits allow certain coral lineages to persist through stress while others disappear? Why are mesophotic habitats less affected by thermal stress than their euphotic counterparts? Furthermore, is this observed coral resilience limited to short timescales or does it persist over long, geological timescales? To address these questions, we must look at the fossil record. Over the past 250 million years, coral reefs (those primarily built by scleractinian corals) have endured repeated climate extremes, tectonic shifts, sea-level change, and mass mortality events. Fossil data can reveal which communities and species have persisted, which collapsed, and under what conditions recovery was possible. More importantly, how might those insights from the fossil record be applied to current conservation priorities? In this talk, I will discuss why palaeontology should be in the spotlight to guide the protection of reefs. By bridging palaeontology, neontology, and conservation science—and by empowering the next generation of reef scientists— we can act more effectively to address the urgent challenges of the Anthropocene.

## Invited talks

### Ecosystem engineering in coral reef biodiversity hotspots throughout the Phanerozoic  
**Alison Cribb, University of Southampton, UK**

Ecosystem engineers – organisms whose activities and behaviours change resource availability to impact the overall habitability of their environments – are some of the most important keystone animals in our oceans. As reef-builders, corals are critical ecosystem engineers in our oceans today, engineering the habitats that host some of the Earth’s most important biodiversity hotspots. While the ecosystem engineering impacts of corals in biodiversity hotspots are relatively well understood today, their roles in ancient reef ecosystems for creating biodiversity hotspots are less well constrained. Here, we identify occurrences of coral reef biodiversity hotspots throughout the Phanerozoic and quantify the magnitude of reef-building ecosystem engineers’ impacts on biodiversity. Using fossil occurrences from the Paleobiology Database, we apply approaches from ecological meta-analyses to identify when coral ecosystem engineers had significantly positive impacts on biodiversity relative to other communities and regions. We also mapped occurrences of all corals, all coral-associated taxa, and those found in formations that preserve biodiversity hotspots through time and space. We find evidence for coral reef biodiversity hotspots in the Ordovician as early as the Tremadocian, becoming a major feature of tropical ecosystems by the Sandbian. However, we also find that coral reef biodiversity hotspots are not a permanent feature of the marine biosphere once they emerge. Some intervals of Earth history see near or total losses of coral reef biodiversity hotspots. We then investigated the controls on coral biodiversity hotspots to identify why some time periods are more characterised by hotspots than others. We find a unique combination of ecology, climate, and biogeography: coral reef biodiversity hotspots, perhaps unsurprisingly, require diverse coral ecosystem engineers, an abundance of tropical coastlines, and moderate climates.

### The evolution of coral photosymbiosis  
**Jonathan Jung, Max-Planck Institute for Chemistry, Germany**

It was long debated whether photosymbiosis first arose in the Triassic, with the emergence of scleractinian corals, or if it was already prevalent amongst older coral groups that have since gone extinct. Using, coral-bound nitrogen isotopes (expressed as CB-δ15N = [(15N/14N)sample / (15N/14N)air - 1]*1000 in ‰), we found the first conclusive geochemical evidence that Mid-Devonian colonial tabulate and dendroid rugose corals hosted active photosymbionts, while solitary and ceroid rugose corals did not. A remarkable finding of our study on Mid-Devonian reefs was the consistent finding that all colonial tabulate corals analyzed hosted photosymbionts whereas all solitary rugose corals did not. The evolutionary history of this symbiosis might clarify its organismal and environmental roles in the success and demise of Paleozoic corals. Building on these findings, we analyzed colonial tabulate and solitary rugose corals of the Pirgu limestone formation of Estonia and Gotland in Sweden which show the emergence of a CB-δ15N difference between colonial tabulate and solitary rugose during the late Ordovician while at the same time showing increasing CB-δ15N values. This suggests a potential emergence of photosymbiosis during the late Ordovician cooling, while increasing δ15N values are consistent with expanded anoxia, potentially caused by intensified phosphorus recycling in the Ordovician ocean.

### Intra-crystalline amino acids as indicator for recrystallisation and preservation of fossil corals  
**Luisa Meiritz, GEOMAR, Germany**  

Tropical corals are widely used for paleoclimate reconstructions to depict climate and 
environmental conditions in high resolution. However, the further back in time, the more difficult it is to find well-preserved corals for this type of reconstruction. Most of the measurable element and isotope ratios, which serve as climate proxies, are altered by diagenetic recrystallisation processes over geological timescales and thus become impractical for climatic reconstruction. Nonetheless, a novel methodological approach provides new opportunities for the reconstruction of climate indicators in corals despite of their critical geochemical preservation. This approach incorporates the analysis of organic intra-crystalline material (more specifically: amino acids) in coral skeletons that serves indicator for the state of their preservation. This study will provide a first approach to quantify intra-crystalline amino acid content and the preservation of the inorganic coral skeleton using high resolution HPLC amino acid racemization analysis and X-ray powder diffraction analyses. Additionally, two morphologically different coral species (Porites sp. thin theca walls, and Diploria sp. thick theca walls) from Eocene, Pliocene and Miocene deposits are analyzed to compare their preservation potential over geological timescales.

### Quantifying novel marine ecologies across time scales  
**Emer Cunningham, The University of Queensland, Australia**  

Global change is pushing biodiversity towards unprecedented, “novel” ecological states. There is great potential for the concept of ecological novelty to help uncover patterns and drivers of significant ecosystem change through time, but quantitative studies are currently lacking. In this talk, I introduce a recent framework that uses time series data to empirically detect novel states, and showcase how we have applied this framework across various taxa and time scales. Over the past millennium, we observe novel shifts in coral genus composition along the Australian coast, which occur more frequently and independently than equally significant functional compositional shifts. Over recent decades, zooplankton communities show similar patterns in taxonomic and functional novelty through time, which appear uncorrelated with novel environmental conditions. These empirical studies offer new insights into how global marine ecologies have significantly shifted in the past, which can serve as analogues for a widely predicted future of novel ecosystems.

### Integrating fossil data in paleoecological niche models improves predictions of future habitat for key Caribbean reef corals  
**Claire Williams, University of Texas at Austin, USA**  

Ecological niche models (ENMs) help assess the abiotic preferences of species by linking their occurrences to the environmental conditions in which they live. This study applies ENMs to assess four critical reef-building Caribbean coral species. We first examine whether their ecological niches have remained consistent (niche stability) from the Holocene to the Present, and whether incorporating data from past warm climate periods better estimates the corals' fundamental niche. Given a finding of niche stability, we used the ENM-reconstructed niche characteristics to predict area and location of suitable habitat for future climate scenarios in the years 2050 and 2100. Our findings show that including Holocene fossil data broadens the niche hypervolume, resulting in a greater projection of suitable habitats than models based solely on modern data. Although our models show that suitable habitats exist for these corals in 2100, suitable habitat declines dramatically (45-100% decrease in area from Present), there is a significant restriction of lower latitude habitat suitability, and marine protected areas do not overlap the majority of future suitable habitat. These results support that preventing significant degradation of these vital ecosystems requires action towards reducing emissions and expanding protected areas in the northern Caribbean.

### Coral reefs from the early Miocene of the La Guajira Peninsula, Colombian Caribbean  
**Paola Florez, MoAm S.A.S., Colombia**  

The Oligocene–Miocene transition was a period of significant change for coral reefs in the Caribbean Basin. However, the fossil reefs in the southern part of the basin have been poorly studied. In the La Guajira Peninsula, located in the northeast of Colombia, rich fossiliferous deposits with corals from the early Miocene outcrop at the foothills of the Cocinas, Jarara, and Macuira ranges. This work provides information on the sedimentology and the spatial distribution of the reef deposits of the Siamaná Formation (Aquitanian–Budigalian), as well as a paleoenvironmental interpretation. Furthermore, a comprehensive inventory of the reef-building species from the Siamaná and Jimol (Burdigalian) Formations is presented. The results indicated that during the early Miocene, a reef system was present on the southeastern margin of the Jarara paleoisland (current Jarara range) in optimal development conditions. The landscape was characterized by two types of reefs: patch reefs, which were distributed in a shallow lagoon area, with reduced inputs of terrestrial material from the Jarara paleoisland, and discontinuous barrier reefs that surrounded the same paleoisland. In both cases, the scleractinian corals were the main bioconstructors. Both types of reefs were dominated by colonies of massive (domestones), erect (pillarstones), and their combinations (mixstones) forms, in clear and shallow water environments. Within bioclastic sediments surrounding the coral colonies (rudstone), rubble of mollusks, coral algae, benthic foraminifera, and echinoderms are the most common. Regarding the identified coral fauna, 32 morphospecies belonging to two orders (Scleractinia and Anthoathecata), 12 families, and 15 genera were found. Most of these species became extinct in two subsequent pulses: at the end of the early Miocene and during the transition from the Pliocene to the Pleistocene. Only three species: Montastraea cavernosa, Siderastrea siderea and Millepora alcicornis, are still present in modern Caribbean reefs.

### Recolonisation strategies of early animals in the Avalon (Ediacaran 574 – 560 Ma)  
**Nile Stephenson, University of Cambridge, UK**  

The first geographically widespread metazoans are found in the Avalon assemblage (Ediacaran; 574 – 560 Ma). These early animals were regularly disturbed by sedimentation events such as ash flows and turbidites, leading to an apparent “resetting” of communities. However, it is not clear how biological legacies – remains or survivors of disturbance events – influenced community ecology in the Avalon. Here, we use spatial point process analysis on 19 Avalon palaeocommunities to test whether two forms of biological legacy (fragmentary remains of Fractofusus and surviving frondomorphs) impacted the recolonisation dynamics of Avalon palaeocommunities. We found that densities of Fractofusus were increased around the Fractofusus fragments, suggesting that they helped to recolonise the post-disturbance substrate, potentially contributing to the Fractofusus dominance found in 8 of the 19 palaeocommunities. However, we found no such effects for survivor fronds. Our results suggest that the evolution of height was for long-distance dispersal rather than local recolonisation. In modern deep-sea environments, there is a trade-off between local and long-distance dispersal, and our work demonstrates that this differentiation of reproductive strategies had already developed in the early animals of the Avalon.

### Reconstructing redox conditions and assessing its impact on reef metazoan distribution on the Cambrian Siberian Platform  
**Ruaridh Alexander, University of Edinburgh, UK**  

Whether metazoan diversification during the Cambrian Radiation (ca. 539–515 million years ago) was driven by increased marine oxygenation remains highly debated. Global geochemical proxies have inferred global oceanic oxygenation events, however, the degree and extent of shallow oxygenation and its relationship to diversification remains uncertain. To resolve this, we interrogate an interval from ca. 527-519 Ma, by integrating the spatial and temporal distribution of shallow water, in situ reef metazoans, and the first large calcified motile bilaterians (trilobites), with high-resolution multi-proxy redox data through the highly biodiverse lower Cambrian Siberian Platform. We document primarily dysoxic water column conditions in sections with in situ metazoans and reef assemblages, suggesting that early Cambrian reef metazoans and motile skeletal benthos did not require near-modern dissolved oxygen levels to evolve. Punctuating background oxygen levels are 1-3 Myr oceanic oxygenation events (OOEs) coincident with positive global carbon isotope excursions that led to modestly elevated oxygen levels. These events correspond to regional increases in biodiversity, rates of origination, and habitat expansion, notably in the reef-building archaeocyath sponges and in the trilobites, shortly after their first appearances. These oxygenation events postdate the first appearance of trilobites and archaeocyaths, however, and are thus decoupled from evolutionary innovation. This regional biotic response to episodes of modestly elevated oxygen levels suggests that elevated oxygen levels enabled habitat expansion, which in turn likely promoted diversification within these groups through a range of other selection pressures. Given the global nature of these oxygenation events, implied by the carbon isotope record, the expansion and contraction of habitable space on biodiverse shallow marine platforms due to dynamic redox conditions offers a potentially globally-applicable model for biodiversification.

### A global phylogeny reveals the evolutionary history of stony corals: insights on pervasive morphological convergence  
**Claudia Vaga, Smithsonian Institution, USA**  

Global climate change is impacting coral reefs worldwide. Understanding how stony corals, the primary architects of both shallow and deep reef ecosystems, responded to past environmental challenges is key to predicting their future. However, reliable phylogenetic reconstructions and resolution of longstanding evolutionary questions of the order Scleractinia have been hampered by a substantial underrepresentation of azooxanthellate and deep-sea species and a paucity of available molecular markers. Our comprehensive, time-calibrated molecular phylogenetic analysis, which includes hundreds of newly sequenced coral taxa, sheds new light on the deep-time evolution of scleractinian corals. We found that the most recent common ancestor of Scleractinia is dated to occur ~460 million years ago and was likely solitary, heterotrophic, and free-living, thriving in both shallow and deep waters. Symbiosis with photosynthetic dinoflagellates, established ~300 million years ago and spurred coral diversification. However, only a few photosymbiotic lineages survived major environmental disruptions in the Mesozoic era. In contrast, solitary, heterotrophic corals with flexible depth and substrate preferences probably thrived in the deep sea following environmental disturbance events. Our analyses reveal greater vulnerability and reduced resilience in shallow-water symbiotic corals compared to their deep-water, solitary counterparts. Moreover, in our phylogenomic reconstruction several genera and families were recovered as polyphyletic assemblages highlighting pervasive macro and micromorphological convergence in the order, thus underscoring major challenges in reliably placing fossil taxa in Scleractinia clade stems.

### Stromatoporoid phases  
**Patrycja Dworczak - Polish Geological Institute, Poland and GeoZentrum Nordbayern-FAU, Germany**  

Reef ecosystems dominated sediment production on tropical carbonate platforms throughout the Phanerozoic Eon, both in calcitic and aragonitic seas. Growth rates and carbonate accumulation rates of Palaeozoic reefs are poorly known, because their framework-building organisms (e.g., rudist bivalves, hypercalcified sponges, tabulate and rugose corals), lacking verified evidence of growth rates, are now extinct. However, their fossil remains commonly show well-preserved and easily recognizable growth banding. These increments are characterized by an alternation of dense and less dense skeletal layers, which may reflect annual, monthly or daily rhythms. Among the important Palaeozoic reef-builders in particular, stromatoporoids exhibit exquisite incremental banding (Young & Kershaw, 2005). The aim of this project is to redefine the approach to the study of stromatoporoid skeletal structures by applying the concept of "phases" introduced by Stearn (1989). The research focused on the analysis of variations in growth structures, which may correspond to growth rates. These phases are interpreted as resulting from episodic interruptions in growth. Additionally, well-preserved stromatoporoid material from Gotland allowed for the analysis of complete skeletons, rather than use of small fragments as in earlier studies. Thus, special attention was placed on identification and interpretation of growth interruption layers in stromatoporoid skeletons, which are typically recognized in specimens that have the margins of the skeletons preserved, to allow investigation of the relationship between phases and potential environmental events.

### Contrasting response of reefs versus level bottom communities to the Early Jurassic environmental changes in Morocco  
**Sinjini Sinha - West Virginia University, USA**  

The Pliensbachian/Toarcian boundary event (~183.1 million years ago) and Toarcian Oceanic Anoxic Event or Jenkyns Event (~182.7 million years ago) represent two of the most severe environmental perturbations of the Early Jurassic Epoch, leading to global marine ecosystem disruption and biotic crises. Previous work on these crises has implicated warming-induced anoxia as the primary driver for the extinctions. Recent studies, however, show elevated extinction rates in well-oxygenated basins, such as the Lusitanian Basin in Portugal, and the Iberian Basin in Spain. Here, we report and compare the differential responses of level bottom (non-reefal) versus reef communities to the environmental stressors from multiple sites in the Central High Atlas Mountains of Morocco. The studied Moroccan sites preserve expanded records of Lower Jurassic strata along an onshore-offshore depth transect, capturing both the Pliensbachian/Toarcian boundary and the Jenkyns Event. We use basin-wide sequence stratigraphy to correlate the occurrence, abundance, and diversity of the level-bottom communities (e.g., bivalves, brachiopods) across multiple sections in the Central High Atlas Basin of Morocco. There was no significant loss of taxonomic diversity or functional groups across the two events, instead there was a diversification amongst the macrofaunal communities after the Toarcian event. The resilience of level bottom communities is in stark contrast to the multi-phased collapse of reefs and extinction of corals and foraminifera, which indicate that environmental stressors were not uniformly detrimental to the fauna of the Central High Atlas basin. Despite the extinctions, coral reef communities recovered relatively rapidly in Morocco. The quicker recovery of reef organisms combined with no significant diversity loss amongst level bottom communities, indicates that Morocco was likely a low latitude refuge for Early Jurassic communities. These new stratigraphic paleobiological data are critical to understanding organism survival during the Early Jurassic environmental perturbation and serve as important analogues for modern ocean ecosystems. 